### ISSUE TITLE
Attributes are symbols, policyfiles don't take symbols

### ISSUE THREAD

**Issue by mattray** [jjasghar/chefdk-cookbook#4]
Why not strings? If I try to use a symbol in my policyfile, I get this:

       Error: Failed to update Policyfile lock
       Reason: (ChefDK::InvalidPolicyfileAttribute) Invalid type in attributes. Only Hash, Array, String, Integer, Float, true, false, and nil are accepted. You gave :stable (Symbol)

**Comment by jjasghar** [comment]
Fixed via https://github.com/jjasghar/chefdk-cookbook/commit/5e4452aabe7224409fc77138ec53b5c5de41cabc

Pushed to the supermarket also.

```
~/repo/cookbooks/chefdk-cookbook on master [d]± chef-run 10.0.0.122 . --password admini --sudo-password admini --user admini
[✔] Packaging cookbook... done!
[✔] Generating local policyfile... exporting... done!
[✔] Applying chefdk::default from /Users/jjasghar/repo/cookbooks/chefdk-cookbook to target.
└── [✔] [10.0.0.122] Successfully converged chefdk::default.
```

**Comment by mattray** [comment]
💥 Thanks JJ!

**Comment by mattray** [comment]
The ['chefdk']['channel'] is still a symbol.

**Comment by jjasghar** [comment]
It seems that chef-ingredient requires it to be: https://github.com/chef-cookbooks/chef-ingredient#properties

I did test like above and it did work with `chef-run`..... so maybe something is different?
